<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="auto_tests" skips="1" tests="3" time="1003.315"><testcase classname="auto.platform-clustering.clusteringtests.test_cluster_join" file="../../lib/python2.7/site-packages/clusteringtests/test_cluster_join.py" line="15" name="test_max_nodes" time="801.00904727"></testcase><testcase classname="auto.platform-clustering.clusteringtests.test_cluster_unconfigure" file="../../lib/python2.7/site-packages/clusteringtests/test_cluster_unconfigure.py" line="8" name="test_unconfiguring_a_cluster" time="0.000264883041382"><skipped message="Investigate why this fails" type="pytest.skip">../../lib/python2.7/site-packages/clusteringtests/test_cluster_unconfigure.py:8: &lt;py._xmlgen.raw object at 0x7fa1ebfc2750&gt;</skipped></testcase><testcase classname="auto.platform-clustering.clusteringtests.test_eth_ip_addresses" file="../../lib/python2.7/site-packages/clusteringtests/test_eth_ip_addresses.py" line="58" name="test_add_and_remove_ip_address_to_eth0" time="146.635885"><failure message="CliCommandFailed: CliCommandFailed(rc=1, timestamp=2017-09-25T07:46:21.063509+01:00, output=The specified IP address is already in use).">node = &lt;core.node.Node object at 0x7fa1f6132490&gt;
test_logger = &lt;logging.Logger object at 0x7fa1f61327d0&gt;

    def test_add_and_remove_ip_address_to_eth0(node, test_logger):
        fake_ip1 = &apos;203.0.113.242&apos;
        fake_ip2 = &apos;203.0.113.1&apos;
        fake_ip3 = &apos;203.0.113.112&apos;
    ...SNIP...
E                                   CliCommandFailed: CliCommandFailed(command=&quot;evsipaddr &quot;-e&quot; &quot;0&quot; &quot;-a&quot; &quot;-i&quot; &quot;203.0.113.1&quot; &quot;-m&quot; &quot;255.255.0.0&quot; &quot;-p&quot; &quot;eth0&quot;&quot;, rc=1, timestamp=2017-09-25T07:46:21.063509+01:00, output=&quot;The specified IP address is already in use.&quot;)

../../local/lib/python2.7/site-packages/ssh/ssh.py:724: CliCommandFailed</failure></testcase></testsuite>
